# Generated by Django 6.0.6 on 2026-07-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shoes', 'Shoes'), ('Watch', 'Watch'), ('Headphones', 'Headphones')], default='Shoes', max_length=100),
        ),
    ]
